"""Insight Engine — generates cross-module insights and recommendations.

Insights are generated by analyzing data across all modules and identifying
gaps, opportunities, and improvements. They power the AI Coach, dashboard,
and notification system with context-aware suggestions.
"""

import logging

from app.extensions import db

logger = logging.getLogger(__name__)


def generate_insights(user_id: int) -> list[dict]:
    """Generate all insights for a user by analyzing across modules."""
    insights = []

    insights.extend(_skill_gap_insights(user_id))
    insights.extend(_resume_insights(user_id))
    insights.extend(_project_insights(user_id))
    insights.extend(_application_insights(user_id))
    insights.extend(_roadmap_insights(user_id))
    insights.extend(_integration_insights(user_id))
    insights.extend(_readiness_insights(user_id))

    _persist_insights(user_id, insights)

    return insights


def _skill_gap_insights(user_id: int) -> list[dict]:
    """Identify skill-related gaps and opportunities."""
    from app.intelligence.services.skill_graph_engine import (
        get_skill_graph, get_weakest_skills,
    )
    from app.career.models import CareerProfile

    insights = []
    profile = CareerProfile.query.filter_by(user_id=user_id).first()

    if not profile or not profile.target_role:
        return insights

    graph = get_skill_graph(user_id)
    weakest = get_weakest_skills(user_id)

    if weakest:
        skills_list = ", ".join(s["skill"] for s in weakest[:3])
        insights.append({
            "insight_type": "skill_gap",
            "title": "Skills That Need Attention",
            "description": f"Your lowest-confidence skills are {skills_list}. "
                           f"Focusing on these could significantly boost your career readiness.",
            "impact_score": 7,
            "category": "skills",
            "action_link": "/roadmaps",
            "action_label": "View Learning Roadmaps",
        })

    if graph["total"] < 5:
        insights.append({
            "insight_type": "skill_diversity",
            "title": "Build Your Skill Set",
            "description": "You have fewer than 5 skills tracked. Adding more skills "
                           "from your resume, GitHub, or LinkedIn will unlock better "
                           "career recommendations.",
            "impact_score": 8,
            "category": "skills",
            "action_link": "/career-profile/wizard",
            "action_label": "Add Skills",
        })

    return insights


def _resume_insights(user_id: int) -> list[dict]:
    """Identify resume-related improvements."""
    from app.resume.models import Resume

    insights = []
    resume = Resume.query.filter_by(user_id=user_id).first()

    if not resume:
        insights.append({
            "insight_type": "resume_missing",
            "title": "Create Your Resume",
            "description": "You haven't created a resume yet. A strong resume is "
                           "essential for job applications and ATS scoring.",
            "impact_score": 9,
            "category": "resume",
            "action_link": "/resume",
            "action_label": "Build Resume",
        })
        return insights

    if not resume.summary:
        insights.append({
            "insight_type": "resume_summary",
            "title": "Add a Professional Summary",
            "description": "Your resume is missing a professional summary. "
                           "This is the first thing recruiters see.",
            "impact_score": 6,
            "category": "resume",
            "action_link": "/resume",
            "action_label": "Edit Resume",
        })

    if resume.experience:
        has_metrics = False
        for exp in resume.experience:
            if isinstance(exp, dict) and exp.get("description"):
                if any(char.isdigit() for char in str(exp.get("description", ""))):
                    has_metrics = True
                    break
        if not has_metrics:
            insights.append({
                "insight_type": "resume_metrics",
                "title": "Add Measurable Achievements",
                "description": "Your experience descriptions lack metrics and numbers. "
                               "Adding quantified achievements can improve ATS score significantly.",
                "impact_score": 8,
                "category": "resume",
                "action_link": "/resume",
                "action_label": "Improve Resume",
            })

    if resume.skills and len(resume.skills) < 8:
        insights.append({
            "insight_type": "resume_skills",
            "title": "Expand Your Skills Section",
            "description": f"You only have {len(resume.skills)} skills on your resume. "
                           f"Adding more relevant skills increases keyword match with job descriptions.",
            "impact_score": 5,
            "category": "resume",
            "action_link": "/resume",
            "action_label": "Edit Skills",
        })

    return insights


def _project_insights(user_id: int) -> list[dict]:
    """Identify project-related improvements."""
    from app.intelligence.models import CanonicalProject, ProjectIntelligence

    insights = []
    projects = CanonicalProject.query.filter_by(user_id=user_id).all()

    if not projects:
        insights.append({
            "insight_type": "project_missing",
            "title": "Showcase Your Work",
            "description": "No projects found. Adding projects from GitHub or manually "
                           "will strengthen your portfolio and improve interview prep.",
            "impact_score": 7,
            "category": "projects",
            "action_link": "/projects",
            "action_label": "Add Projects",
        })
        return insights

    # Check for projects without intelligence analysis
    unanalyzed = [p for p in projects if not ProjectIntelligence.query.filter_by(project_id=p.id).first()]
    if unanalyzed:
        insights.append({
            "insight_type": "project_analysis",
            "title": "Analyze Your Projects",
            "description": f"{len(unanalyzed)} project(s) haven't been analyzed yet. "
                           f"Analysis reveals skill inferences and resume value.",
            "impact_score": 4,
            "category": "projects",
            "action_link": "/projects",
            "action_label": "Analyze Projects",
        })

    # Check for missing tests
    missing_tests = []
    for p in projects:
        pi = ProjectIntelligence.query.filter_by(project_id=p.id).first()
        if pi and pi.missing_tests:
            missing_tests.append(p.name)
    if missing_tests:
        names = ", ".join(missing_tests[:3])
        insights.append({
            "insight_type": "project_tests",
            "title": "Add Tests to Your Projects",
            "description": f"Projects like {names} are missing tests. Adding tests "
                           f"improves resume value and demonstrates quality engineering.",
            "impact_score": 5,
            "category": "projects",
            "action_link": "/projects",
            "action_label": "View Projects",
        })

    return insights


def _application_insights(user_id: int) -> list[dict]:
    """Identify application-related insights."""
    from app.jobs.models import Job

    insights = []
    jobs = Job.query.filter_by(user_id=user_id).all()

    if not jobs:
        insights.append({
            "insight_type": "application_start",
            "title": "Start Applying",
            "description": "You haven't applied to any jobs yet. Start exploring "
                           "opportunities that match your skills.",
            "impact_score": 8,
            "category": "applications",
            "action_link": "/jobs",
            "action_label": "Find Jobs",
        })
        return insights

    active = sum(1 for j in jobs if j.status in ("applied", "interview", "offer"))
    rejected = sum(1 for j in jobs if j.status == "rejected")

    if active == 0 and rejected > 0:
        insights.append({
            "insight_type": "application_pipeline",
            "title": "Rebuild Your Pipeline",
            "description": "Your application pipeline is empty. Consider updating your "
                           "resume and trying again with a refined strategy.",
            "impact_score": 7,
            "category": "applications",
            "action_link": "/jobs",
            "action_label": "Browse Jobs",
        })
    elif active < 3:
        insights.append({
            "insight_type": "application_volume",
            "title": "Increase Application Volume",
            "description": f"You have only {active} active application(s). "
                           f"Aim for at least 5-10 active applications to improve interview odds.",
            "impact_score": 6,
            "category": "applications",
            "action_link": "/jobs",
            "action_label": "Apply More",
        })

    upcoming_interviews = sum(1 for j in jobs if j.status == "interview")
    if upcoming_interviews > 0:
        insights.append({
            "insight_type": "interview_upcoming",
            "title": f"Upcoming Interview{'s' if upcoming_interviews > 1 else ''}",
            "description": f"You have {upcoming_interviews} interview{'s' if upcoming_interviews > 1 else ''} "
                           f"scheduled. Check the Interview Hub for preparation resources.",
            "impact_score": 9,
            "category": "interviews",
            "action_link": "/coach",
            "action_label": "Prepare for Interview",
        })

    return insights


def _roadmap_insights(user_id: int) -> list[dict]:
    """Identify roadmap-related insights."""
    from app.career.models import Roadmap

    insights = []
    roadmaps = Roadmap.query.filter_by(user_id=user_id).all()

    if not roadmaps:
        from app.career.models import CareerProfile
        profile = CareerProfile.query.filter_by(user_id=user_id).first()
        if profile and profile.target_role:
            insights.append({
                "insight_type": "roadmap_generate",
                "title": "Generate Your Learning Roadmap",
                "description": f"You're targeting {profile.target_role} but don't have "
                               f"a learning roadmap yet. Generate one to track your progress.",
                "impact_score": 8,
                "category": "learning",
                "action_link": "/roadmaps",
                "action_label": "Generate Roadmap",
            })
        return insights

    active = [r for r in roadmaps if r.status == "active"]
    for r in active:
        if r.progress and r.progress < 30:
            insights.append({
                "insight_type": "roadmap_progress",
                "title": f"Keep Going: {r.title}",
                "description": f"You're {r.progress}% through your {r.title}. "
                               f"Consistent progress of even 1 lesson per day adds up fast.",
                "impact_score": 5,
                "category": "learning",
                "action_link": f"/roadmaps?id={r.id}",
                "action_label": "Continue Learning",
            })
            break

    return insights


def _integration_insights(user_id: int) -> list[dict]:
    """Identify integration-related insights."""
    from app.integrations.models import Integration

    insights = []
    github = Integration.query.filter(
        Integration.user_id == user_id,
        Integration.provider == "github",
        Integration.sync_status.in_(["connected", "syncing"]),
    ).first()
    linkedin = Integration.query.filter(
        Integration.user_id == user_id,
        Integration.provider == "linkedin",
        Integration.sync_status.in_(["connected", "syncing"]),
    ).first()

    if not github:
        insights.append({
            "insight_type": "github_connect",
            "title": "Connect GitHub",
            "description": "Connecting GitHub automatically imports your repositories "
                           "as projects, detects your skills, and improves your portfolio score.",
            "impact_score": 7,
            "category": "integrations",
            "action_link": "/settings?tab=integrations",
            "action_label": "Connect GitHub",
        })

    if not linkedin:
        insights.append({
            "insight_type": "linkedin_connect",
            "title": "Import LinkedIn Profile",
            "description": "Importing LinkedIn adds your experience, education, and skills "
                           "automatically. No manual data entry needed.",
            "impact_score": 6,
            "category": "integrations",
            "action_link": "/settings?tab=integrations",
            "action_label": "Connect LinkedIn",
        })

    return insights


def _readiness_insights(user_id: int) -> list[dict]:
    """Generate insights from readiness score analysis."""
    from app.intelligence.models import UnifiedProfile

    insights = []
    profile = UnifiedProfile.query.filter_by(user_id=user_id).first()

    if not profile:
        return insights

    score = profile.career_readiness_score or 0

    if score < 30:
        insights.append({
            "insight_type": "readiness_low",
            "title": "Build Your Foundation",
            "description": "Your Career Readiness Score is low. Focus on the basics: "
                           "create a resume, add skills, and start a learning roadmap.",
            "impact_score": 10,
            "category": "readiness",
            "action_link": "/onboarding",
            "action_label": "Complete Setup",
        })
    elif score < 60:
        # Find weakest area
        areas = {
            "Skills": profile.skill_readiness_score or 0,
            "Projects": profile.project_readiness_score or 0,
            "Resume": profile.resume_readiness_score or 0,
            "Experience": profile.experience_readiness_score or 0,
            "Interviews": profile.interview_readiness_score or 0,
            "Applications": profile.application_readiness_score or 0,
            "Learning": profile.learning_readiness_score or 0,
        }
        weakest = min(areas, key=areas.get)
        insights.append({
            "insight_type": "readiness_improve",
            "title": f"Boost Your {weakest} Score",
            "description": f"Your {weakest.lower()} score ({areas[weakest]}/100) is your "
                           f"biggest growth opportunity. Improving this will raise your "
                           f"overall Career Readiness.",
            "impact_score": 7,
            "category": "readiness",
            "action_link": "/dashboard",
            "action_label": "View Dashboard",
        })

    return insights


def _persist_insights(user_id: int, insights: list[dict]) -> None:
    """Store generated insights in the database."""
    from app.intelligence.models import IntelligenceInsight

    # Mark existing insights as dismissed (they'll be replaced)
    existing = IntelligenceInsight.query.filter_by(user_id=user_id, is_dismissed=False).all()
    for ins in existing:
        ins.is_dismissed = True

    for ins_data in insights:
        insight = IntelligenceInsight(
            user_id=user_id,
            insight_type=ins_data["insight_type"],
            title=ins_data["title"],
            description=ins_data["description"],
            impact_score=ins_data["impact_score"],
            category=ins_data["category"],
            action_link=ins_data.get("action_link"),
            action_label=ins_data.get("action_label"),
        )
        db.session.add(insight)

    db.session.commit()


def get_insights(user_id: int, limit: int = 20) -> list[dict]:
    """Get the latest insights for a user."""
    from app.intelligence.models import IntelligenceInsight

    insights = (
        IntelligenceInsight.query.filter_by(user_id=user_id, is_dismissed=False)
        .order_by(IntelligenceInsight.impact_score.desc(), IntelligenceInsight.created_at.desc())
        .limit(limit)
        .all()
    )
    return [
        {
            "id": i.id,
            "insight_type": i.insight_type,
            "title": i.title,
            "description": i.description,
            "impact_score": i.impact_score,
            "category": i.category,
            "action_link": i.action_link,
            "action_label": i.action_label,
            "created_at": i.created_at.isoformat() if i.created_at else None,
        }
        for i in insights
    ]
