"""revert_consolidation_changes

Revision ID: 1b0f9993867d
Revises: b1c2d3e4f5a6
Create Date: 2026-07-11 09:38:23.262205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0f9993867d'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_versions_by_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('resume_snapshot', sa.JSON(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('job_description_used', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_jobs_opportunity_id'), type_='foreignkey')
        batch_op.drop_column('opportunity_id')

    with op.batch_alter_table('resume_files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_resume_files_resume_id'), type_='foreignkey')
        batch_op.drop_column('resume_id')

    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_resume_versions_opportunity_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_resume_versions_user_id'), type_='foreignkey')
        batch_op.drop_column('job_description_used')
        batch_op.drop_column('ats_score')
        batch_op.drop_column('opportunity_id')
        batch_op.drop_column('company_name')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('saved_opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applied_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('application_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_opportunities', schema=None) as batch_op:
        batch_op.drop_column('application_status')
        batch_op.drop_column('applied_at')

    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('opportunity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ats_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('job_description_used', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_resume_versions_user_id'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_resume_versions_opportunity_id'), 'opportunities', ['opportunity_id'], ['id'])

    with op.batch_alter_table('resume_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_resume_files_resume_id'), 'resumes', ['resume_id'], ['id'])

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opportunity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_jobs_opportunity_id'), 'opportunities', ['opportunity_id'], ['id'])

    op.drop_table('resume_versions_by_company')
    # ### end Alembic commands ###
