"""add personalized roadmap fields and lesson_progress table

Revision ID: 71e144b05da7
Revises: f6aad29227e0
Create Date: 2026-07-12 11:22:32.999763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e144b05da7'
down_revision = 'f6aad29227e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.String(length=100), nullable=False),
    sa.Column('phase_id', sa.String(length=100), nullable=False),
    sa.Column('module_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'lesson_id', name='uq_roadmap_lesson')
    )
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('current_phase_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_module_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_lesson_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weekly_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_activity_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.drop_column('started_at')
        batch_op.drop_column('last_activity_at')
        batch_op.drop_column('weekly_hours')
        batch_op.drop_column('streak')
        batch_op.drop_column('current_lesson_id')
        batch_op.drop_column('current_module_id')
        batch_op.drop_column('current_phase_id')
        batch_op.drop_column('definition')

    op.drop_table('lesson_progress')
    # ### end Alembic commands ###
