"""add profile columns for wizard and summary

Revision ID: 7a5344b1a32f
Revises: 553370192dee
Create Date: 2026-07-10 07:37:20.416367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5344b1a32f'
down_revision = '553370192dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('career_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('career_summary')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('timezone')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('gender')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
