"""add reasoning and evidence to AIRecommendation

Revision ID: 8bc52ac994c1
Revises: ec2e7265e065
Create Date: 2026-07-09 15:19:25.096152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc52ac994c1'
down_revision = 'ec2e7265e065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasoning', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('evidence', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_column('evidence')
        batch_op.drop_column('reasoning')

    # ### end Alembic commands ###
