"""add career intelligence engine models

Revision ID: 90d57f3040ab
Revises: 71e144b05da7
Create Date: 2026-07-12 11:55:27.640913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d57f3040ab'
down_revision = '71e144b05da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_user_achievement')
    )
    op.create_table('intelligence_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('action_link', sa.String(length=500), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intelligence_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('action_link', sa.String(length=500), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readiness_score_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('skills_score', sa.Integer(), nullable=True),
    sa.Column('projects_score', sa.Integer(), nullable=True),
    sa.Column('resume_score', sa.Integer(), nullable=True),
    sa.Column('experience_score', sa.Integer(), nullable=True),
    sa.Column('interview_score', sa.Integer(), nullable=True),
    sa.Column('applications_score', sa.Integer(), nullable=True),
    sa.Column('learning_score', sa.Integer(), nullable=True),
    sa.Column('github_score', sa.Integer(), nullable=True),
    sa.Column('linkedin_score', sa.Integer(), nullable=True),
    sa.Column('portfolio_score', sa.Integer(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unified_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dream_role', sa.String(length=255), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('career_stage', sa.String(length=50), nullable=True),
    sa.Column('career_readiness_score', sa.Integer(), nullable=True),
    sa.Column('skill_readiness_score', sa.Integer(), nullable=True),
    sa.Column('project_readiness_score', sa.Integer(), nullable=True),
    sa.Column('resume_readiness_score', sa.Integer(), nullable=True),
    sa.Column('experience_readiness_score', sa.Integer(), nullable=True),
    sa.Column('interview_readiness_score', sa.Integer(), nullable=True),
    sa.Column('application_readiness_score', sa.Integer(), nullable=True),
    sa.Column('learning_readiness_score', sa.Integer(), nullable=True),
    sa.Column('github_readiness_score', sa.Integer(), nullable=True),
    sa.Column('linkedin_readiness_score', sa.Integer(), nullable=True),
    sa.Column('portfolio_readiness_score', sa.Integer(), nullable=True),
    sa.Column('skills_count', sa.Integer(), nullable=True),
    sa.Column('projects_count', sa.Integer(), nullable=True),
    sa.Column('applications_count', sa.Integer(), nullable=True),
    sa.Column('interviews_count', sa.Integer(), nullable=True),
    sa.Column('interviews_completed', sa.Integer(), nullable=True),
    sa.Column('certifications_count', sa.Integer(), nullable=True),
    sa.Column('achievements_count', sa.Integer(), nullable=True),
    sa.Column('roadmaps_count', sa.Integer(), nullable=True),
    sa.Column('roadmap_progress_pct', sa.Integer(), nullable=True),
    sa.Column('events_count', sa.Integer(), nullable=True),
    sa.Column('github_connected', sa.Boolean(), nullable=True),
    sa.Column('linkedin_connected', sa.Boolean(), nullable=True),
    sa.Column('resume_ready', sa.Boolean(), nullable=True),
    sa.Column('resume_has_summary', sa.Boolean(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('last_recalculated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('project_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('languages_detected', sa.JSON(), nullable=True),
    sa.Column('frameworks_detected', sa.JSON(), nullable=True),
    sa.Column('libraries_detected', sa.JSON(), nullable=True),
    sa.Column('complexity', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('estimated_skill_level', sa.String(length=50), nullable=True),
    sa.Column('has_readme', sa.Boolean(), nullable=True),
    sa.Column('has_tests', sa.Boolean(), nullable=True),
    sa.Column('has_documentation', sa.Boolean(), nullable=True),
    sa.Column('has_ci', sa.Boolean(), nullable=True),
    sa.Column('has_dockerfile', sa.Boolean(), nullable=True),
    sa.Column('has_deploy_config', sa.Boolean(), nullable=True),
    sa.Column('lines_of_code', sa.Integer(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('commit_count', sa.Integer(), nullable=True),
    sa.Column('contributor_count', sa.Integer(), nullable=True),
    sa.Column('resume_value', sa.Integer(), nullable=True),
    sa.Column('portfolio_value', sa.Integer(), nullable=True),
    sa.Column('interview_value', sa.Integer(), nullable=True),
    sa.Column('learning_value', sa.Integer(), nullable=True),
    sa.Column('inferred_skills', sa.JSON(), nullable=True),
    sa.Column('missing_tests', sa.Boolean(), nullable=True),
    sa.Column('missing_docs', sa.Boolean(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['canonical_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_project_intel')
    )
    op.create_table('skill_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_lesson_id', sa.String(length=100), nullable=True),
    sa.Column('interview_question', sa.Text(), nullable=True),
    sa.Column('related_skills', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['canonical_certificates.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['canonical_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_name', 'source', name='uq_skill_source')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_evidence')
    op.drop_table('project_intelligence')
    op.drop_table('unified_profiles')
    op.drop_table('readiness_score_snapshots')
    op.drop_table('intelligence_notifications')
    op.drop_table('intelligence_insights')
    op.drop_table('career_achievements')
    # ### end Alembic commands ###
