"""add username language date_format to profiles

Revision ID: 99492d4c5ed8
Revises: 0701ccce171c
Create Date: 2026-07-10 21:09:13.914137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99492d4c5ed8'
down_revision = '0701ccce171c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('date_format', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('date_format')
        batch_op.drop_column('language')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
