"""add password reset fields

Revision ID: 9a777e1cf017
Revises: 54bc28060951
Create Date: 2026-07-08 09:12:50.028283

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9a777e1cf017"
down_revision = "54bc28060951"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("reset_token", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("reset_token_expiry", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("reset_token_expiry")
        batch_op.drop_column("reset_token")

    # ### end Alembic commands ###
