"""Add import_records table

Revision ID: ba4fc0fc69ec
Revises: e09137fa87e3
Create Date: 2026-07-09 12:13:33.835296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4fc0fc69ec'
down_revision = 'e09137fa87e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('normalized_data', sa.JSON(), nullable=True),
    sa.Column('confidence_scores', sa.JSON(), nullable=True),
    sa.Column('import_version', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_records')
    # ### end Alembic commands ###
