"""add target job description field

Revision ID: eea9172a6ec5
Revises: bc2110e8dacc
Create Date: 2026-07-08 16:27:31.932989

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eea9172a6ec5"
down_revision = "bc2110e8dacc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("target_job_description", sa.Text(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.drop_column("target_job_description")

    # ### end Alembic commands ###
