"""extend ResumeVersion

Revision ID: f6aad29227e0
Revises: 1b0f9993867d
Create Date: 2026-07-11 11:36:33.356530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6aad29227e0'
down_revision = '1b0f9993867d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_role', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ats_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ats_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tailored_for_job', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('tailored_for_job')
        batch_op.drop_column('ats_data')
        batch_op.drop_column('ats_score')
        batch_op.drop_column('source')
        batch_op.drop_column('target_role')

    # ### end Alembic commands ###
