"""remove password reset columns

Revision ID: f74109f10f8b
Revises: 90d57f3040ab
Create Date: 2026-07-18 20:28:29.499464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f74109f10f8b'
down_revision = '90d57f3040ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intelligence_notifications')
    op.drop_table('readiness_score_snapshots')
    op.drop_table('skill_evidence')
    op.drop_table('project_intelligence')
    op.drop_table('unified_profiles')
    op.drop_table('intelligence_insights')
    op.drop_table('career_achievements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.create_table('career_achievements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rarity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('unlocked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('career_achievements_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('career_achievements_pkey')),
    sa.UniqueConstraint('user_id', 'code', name=op.f('uq_user_achievement'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('intelligence_insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('insight_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('impact_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('action_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('action_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_dismissed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_applied', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('intelligence_insights_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('intelligence_insights_pkey'))
    )
    op.create_table('unified_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dream_role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('experience_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('career_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('career_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skill_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resume_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interview_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('application_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('learning_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('github_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('linkedin_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('portfolio_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skills_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projects_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('applications_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interviews_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interviews_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certifications_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('achievements_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('roadmaps_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('roadmap_progress_pct', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('events_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('github_connected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('linkedin_connected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('resume_ready', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('resume_has_summary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('onboarding_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_recalculated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('unified_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('unified_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('unified_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('project_intelligence',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('languages_detected', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('frameworks_detected', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('libraries_detected', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('complexity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estimated_skill_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('has_readme', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_tests', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_documentation', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_ci', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_dockerfile', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_deploy_config', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('lines_of_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('commit_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contributor_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resume_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('portfolio_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interview_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('learning_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inferred_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('missing_tests', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('missing_docs', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_analyzed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['canonical_projects.id'], name=op.f('project_intelligence_project_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_intelligence_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_intelligence_pkey')),
    sa.UniqueConstraint('user_id', 'project_id', name=op.f('uq_project_intel'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('skill_evidence',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('evidence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certificate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('roadmap_lesson_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('interview_question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('related_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['canonical_certificates.id'], name=op.f('skill_evidence_certificate_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['canonical_projects.id'], name=op.f('skill_evidence_project_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('skill_evidence_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_evidence_pkey')),
    sa.UniqueConstraint('user_id', 'skill_name', 'source', name=op.f('uq_skill_source'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('readiness_score_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overall_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skills_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projects_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resume_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interview_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('applications_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('learning_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('github_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('linkedin_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('portfolio_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('breakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('readiness_score_snapshots_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('readiness_score_snapshots_pkey'))
    )
    op.create_table('intelligence_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_dismissed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('action_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('action_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('intelligence_notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('intelligence_notifications_pkey'))
    )
    # ### end Alembic commands ###
